# install cockpit
- name: Install cockpit
  apt: 
    name: [cockpit*]
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install cockpit
  yum:
    name: [cockpit*]
    update_cache: yes    
  when: ansible_os_family == "RedHat"
  
- name: Change cockpit port 
  lineinfile:
      dest: /usr/lib/systemd/system/cockpit.socket
      regexp: "ListenStream=9090"
      line: "ListenStream={{cockpit_port}}"
      backrefs: yes 

# configure
- name: Configuration Cockpit Server
  copy:
    src: cockpit.conf
    dest: /etc/cockpit/
    owner: cockpit-ws
    group: cockpit-ws
    force: yes
    mode: 0640

- name: Start & Enable cockpit
  shell: |
    systemctl restart cockpit
    systemctl enable --now cockpit.socket 

- name: Check cockpit Service
  shell: systemctl status cockpit | grep Active*
  register: check_cockpit_service
  notify: check_cockpit_service
